config/routes.rb
Mavens::Application.routes.draw do

  devise_for :users

  resources :events
  resources :carts
  resources :periods
  resources :products
  resources :cart_rows
  resources :product_requests
  resources :inqueries
  match '/profile',  to: 'static_pages#profile'
  root :to => 'static_pages#home'

  get "static_pages/home"
  get "static_pages/about"
  post "static_pages/toggle_admin"
  match '/analytics', to: "static_pages#analytics"
  match '/list', to: "static_pages#user_index"

  resources :period_registrations do
  member do
    post :save_period
  end

  post :save_period, :on => :collection
end
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :require_admin, only: [:analytics, :user_index, :make_admin]
  before_filter :require_sign_in, only: [:profile]

  def profile
    @sessions = PeriodRegistration.find_all_by_user_id(current_user.id, order: "created_at DESC")
    @inqueries = Inquery.find_all_by_user_id(current_user.id, order: "created_at DESC")
    @product_requests = ProductRequest.find_all_by_user_id(current_user.id, order: "created_at DESC")
  end

  def analytics
    user_registrations = User.count(:conditions => ["created_at >= ?", 30.days.ago.to_date], group: "date(created_at)")
    period_registration = PeriodRegistration.count(:conditions => ["created_at >= ?", 30.days.ago.to_date], group: "date(created_at)")
    period_registration_product = PeriodRegistration.joins(:period).where("period_registrations.created_at >= ?", 30.days.ago.to_date).group("periods.product_id").count
    product_requests = ProductRequest.count(:conditions => ["created_at >= ?", 30.days.ago.to_date], group: "date(created_at)")
    product_request_product = ProductRequest.joins(:product).where("product_requests.created_at >= ?", 30.days.ago.to_date).group("product_requests.product_id").count
    inqueries = Inquery.count(:conditions => ["created_at >= ?", 30.days.ago.to_date], group: "date(created_at)")
    inquery_product = Inquery.joins(:product).where("inqueries.created_at >= ?", 30.days.ago.to_date).group("inqueries.product_id").count
    
    @product_count = []

    period_registration_product.each do |key, value|
      @product_count << [Product.find_by_id(key).name, value]
    end

    #product_request_count

    @product_request_product_count = []

    product_request_product.each do |key, value|
     @product_request_product_count << [Product.find_by_id(key).name, value]
    end

    #inquery_product_count

    @inquery_product_count = []

    inquery_product.each do |key, value|
     @inquery_product_count << [Product.find_by_id(key).name, value]
    end

    @user_count = []
    30.times do |day|
      count = user_registrations["#{Date.today - day}"] || 0
      @user_count << count
    end

    @period_registration_count = []
    30.times do |day|
      count = period_registration["#{Date.today - day}"] || 0
      @period_registration_count << count
    end

    @product_request_count = []
    30.times do |day|
      count = product_requests["#{Date.today - day}"] || 0
      @product_request_count << count
    end

    @inquery_count = []
     30.times do |day|
      count = inqueries["#{Date.today - day}"] || 0
      @inquery_count << count
    end
  end

  def user_index
    @users = User.where("email like ?", "%@example.com%").paginate(:page => params[:page]).order("last_name")
  end

  def toggle_admin
    user = User.find_by_id(params[:id])
    user.toggle!(:admin)
    redirect_to list_path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_inquery_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'inquery_chart' },
    legend: {enabled: false},
    title: { text: '30 Day Product Inquiries' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Product Inquiries' },
      allowDecimals: false,
      min: 0
    },
    tooltip: {

      formatter: function () {
        return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' + Highcharts.numberFormat(this.y, 0);
      }
    },    
    series: [{
      pointInterval: <%= 1.day * 1000 %>,
      pointStart: <%= 30.days.ago.at_midnight.to_i * 1000 %>,
      data: <%= @inquery_count.reverse.to_json %>
    }]
  });
});
</script>
<div id="inquery_chart" ></div>

app/views/static_pages/_inquery_product_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'inquery_product' },
    legend: {enabled: false},
    title: { text: '30 Day Product Inquiries by Product' },
     tooltip: {
     formatter: function() {
        return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
     }
  },
     series: [{
                type: 'pie',
                name: 'Browser share',
                data: <%= @inquery_product_count.to_json.html_safe %> 
            }]
  });
});
</script>
<div id="inquery_product" style="min-width: 650px; height: 500px; margin: 0 auto"></div>

app/views/static_pages/_order_charts.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'orders_chart30' },
    legend: {enabled: false},
    title: { text: '30 Day User Registrations' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Users' },
      allowDecimals: false,
      min: 0
    },
    tooltip: {

      formatter: function () {
        return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' + Highcharts.numberFormat(this.y, 0);
      }
    },    
    series: [{
      pointInterval: <%= 1.day * 1000 %>,
      pointStart: <%= 30.days.ago.at_midnight.to_i * 1000 %>,
      data: <%= @user_count.reverse.to_json %>
    }]
  });
});
</script>
<div id="orders_chart30" ></div>
<br />

app/views/static_pages/_period_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'period_chart' },
    legend: {enabled: false},
    title: { text: '30 Day Session Registrations' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Session Registrations' },
      allowDecimals: false,
      min: 0
    },
    tooltip: {

      formatter: function () {
        return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' + Highcharts.numberFormat(this.y, 0);
      }
    },    
    series: [{
      pointInterval: <%= 1.day * 1000 %>,
      pointStart: <%= 30.days.ago.at_midnight.to_i * 1000 %>,
      data: <%= @period_registration_count.reverse.to_json %>
    }]
  });
});
</script>
<div id="period_chart" ></div>

app/views/static_pages/_product_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'product_chart' },
    legend: {enabled: false},
    title: { text: '30 Day Session Registrations By Product' },
     tooltip: {
     formatter: function() {
        return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
     }
  },
     series: [{
                type: 'pie',
                name: 'Browser share',
                data: <%= @product_count.to_json.html_safe %>
            }]
  });
});
</script>
<div id="product_chart" style="min-width: 650px; height: 500px; margin: 0 auto"></div>

app/views/static_pages/_product_request_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'product_request_chart' },
    legend: {enabled: false},
    title: { text: '30 Day Product Sample Requests' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Product Samples' },
      allowDecimals: false,
      min: 0
    },
    tooltip: {

      formatter: function () {
        return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' + Highcharts.numberFormat(this.y, 0);
      }
    },    
    series: [{
      pointInterval: <%= 1.day * 1000 %>,
      pointStart: <%= 30.days.ago.at_midnight.to_i * 1000 %>,
      data: <%= @product_request_count.reverse.to_json %>
    }]
  });
});
</script>
<div id="product_request_chart" ></div>
<br />

app/views/static_pages/_product_request_product_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'product_request_product' },
    legend: {enabled: false},
    title: { text: '30 Day Product Requests by Product' },
     tooltip: {
     formatter: function() {
        return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
     }
  },
     series: [{
                type: 'pie',
                name: 'Browser share',
                data: <%= @product_request_product_count.to_json.html_safe %> 
            }]
  });
});
</script>
<div id="product_request_product" style="min-width: 650px; height: 500px; margin: 0 auto"></div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/analytics.html.erb
<%= render 'order_charts' %>
<%= render 'period_chart' %>
<%= render 'product_chart' %>
<%= render 'product_request_chart' %>
<%= render 'product_request_product_chart' %>
<%= render 'inquery_chart' %>
<%= render 'inquery_product_chart' %>

app/views/static_pages/home.html.erb
 <div class="span9">
    <div class="hero-unit">
      <h1>Welcome to Vetreo's Physician Portal</h1>
       <p>We believe in the work you do everyday, and look forward to helping you provide the best care to your patients using our world class pharmacutical products</a></p>
        <%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-large" %>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <h2>Up Coming Events</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
         <%= link_to "Find Events Near You", events_path, class: "btn btn-primary btn-large" %>
      </div><!--/span-->
      <div class="span4">
        <h2>Medical Inquiries</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <%= link_to "Contact Us", new_inquery_path, class: "btn btn-primary btn-large" %>
      </div><!--/span-->
      <div class="span4">
        <h2>Product Samples</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <%= link_to "Request Samples", products_path, class: "btn btn-primary btn-large" %>
      </div><!--/span-->
    </div><!--/row-->
  </div><!--/span-->
</div><!--/row-->

app/views/static_pages/profile.html.erb
<h2>User Profile</h2>
<br />
<div class="row">
<div class="span1">
    <%if current_user.photo? %>
    <%= image_tag current_user.photo.url(:small) %>
    <% else %>
    <p> No Photo Found. </p><p>To Add Photo Visit: <%= link_to "Change User Settings", edit_user_registration_path %>
    <% end %>
  </div>
  <div class="span4">
    <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
    <br />
    <p>Email: <%= current_user.email %>
    <p>License Number:<%= current_user.license_number %>
    <p>Speciality: <%= current_user.specialty %>
  </div>
  
</div>
<div class="row">
  <div class="span5">
    <br />
    <h3>Sessions</h3>
    <% @sessions.each do |period_registration| %>
    <h4><%= link_to period_registration.period.event.name, period_registration.period.event%><h4>
    <h5><%= period_registration.period.name %></h5>
    <h6><%= period_registration.period.start_time.strftime("%l:%M") %> - 
        <%= period_registration.period.end_time.strftime("%l:%M %P") %> 
        <%=  period_registration.period.event.date.strftime("%b %e, %Y") %></h6>
   <h6><%=  period_registration.period.event.city  %>, <%=period_registration.period.event.state %></h6>
    <p> <%= period_registration.period.description %> <p>
    <hr />
  <% end %>
  </div>
</div>
<div class="row">
  <div class="span5">
    <h3>Medical Inquiries</h3>
    <% @inqueries.each do |inquery| %>
      <h4><%= inquery.product.name %></h4>
      <p><%= inquery.message %><p>
  <% end %>
  <hr />
  </div>

</div>

<div class="row">
  <h3>Product Requests</h3>
  <% @product_requests.each do |product_request| %>
    <h6><%= product_request.product.name %></h6>
      <div class="offset1"><p>Date: <%= time_ago_in_words(product_request.created_at) %> ago</p>
                           <p>Quantity: <%= product_request.quantity %></p>
                           <p>Status: <%= product_request.status %></p>
      </div>
  <% end %>
</div>

app/views/static_pages/user_index.html.erb
<h2>User Index </h2>
<%= page_entries_info @users %>
 <%= will_paginate @users, :renderer => BootstrapPagination::Rails %>
<% @users.each do |user| %>
<div class="row">
  <div class="span2">
     <%= user.first_name %> <%= user.last_name %>
  </div>
  <div class="span3">
   <%= user.email %>
 </div>
 <div class="span3">
 <% if current_user == user %>
  <p> Current User </p>
  <% elsif user.admin? %>
     <%= button_to 'Remove Admin', static_pages_toggle_admin_path(id: user.id), class: "btn-mini btn-danger", method: "post" %>
  <% else %>
     <%= button_to 'Make Admin', static_pages_toggle_admin_path(id: user.id), class: "btn-mini btn-success", method: "post" %>
  <% end %>
  </div>
</div>
 
<% end %>