config/routes.rb
Mavens::Application.routes.draw do

  devise_for :users

  resources :events
  resources :carts
  resources :periods
  resources :products
  resources :cart_rows
  resources :product_requests
  resources :inqueries
  match '/profile',  to: 'static_pages#profile'
  root :to => 'static_pages#home'

  get "static_pages/home"
  get "static_pages/about"
  post "static_pages/toggle_admin"
  match '/analytics', to: "static_pages#analytics"
  match '/list', to: "static_pages#user_index"

  resources :period_registrations do
  member do
    post :save_period
  end

  post :save_period, :on => :collection
end
  

end

app/models/product_request.rb
# == Schema Information
#
# Table name: product_requests
#
#  id         :integer         not null, primary key
#  product_id :integer
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  quantity   :integer
#  street     :string(255)
#  city       :string(255)
#  state      :string(255)
#  zip        :string(255)
#  status     :string(255)
#

class ProductRequest < ActiveRecord::Base
  attr_accessible :product_id, :user_id, :quantity, :street, :city, :state, :zip, :status, :cart_id
  belongs_to :product
  belongs_to :user
  belongs_to :cart

  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates_format_of :zip, :with => /^\d{5}(-\d{4})?$/, :message => "should be in the form 12345 or 12345-1234"
  validates :product_id, :numericality => true
  validates :user_id, :numericality => true

  STATUS = ['New', 'Processing', 'Shipped']
end

app/controllers/product_requests_controller.rb
class ProductRequestsController < ApplicationController

  before_filter :require_sign_in, only: [:new, :create]
  before_filter :require_admin, only: [:index, :show ]

  def index
    @product_requests = ProductRequest.paginate(:page => params[:page]).order("status")
  end
  def show
    render nothing: true
  end


  def new
     @product_request = ProductRequest.new
      @cart = current_cart
  end

  def edit
    @product_request = ProductRequest.find(params[:id])
  end

 def create
  @cart = current_cart
  rows = CartRow.find_all_by_cart_id(@cart.id)
  
  rows.each do |row|
    @product_request = ProductRequest.new(params[:product_request])
    @product_request.user_id = current_user.id
    @product_request.cart_id = @cart.id
    @product_request.product_id = row.product_id
    @product_request.quantity = row.quantity
    unless @product_request.save
      render 'new'
      return
    end
  end
  flash[:success] = "Products Ordered"
  redirect_to cart_url(@cart)
 end

 def update
    @product_request = ProductRequest.find(params[:id])
    if @product_request.update_attributes(params[:product_request])
      redirect_to product_requests_path, flash: {success: "Product Request Updated!"}
    else
      render 'edit'
    end
 end
 
  def destroy
    product_request = ProductRequest.find(params[:id]).destroy
    flash[:success] = "Product Request Deleted."
    redirect_to product_requests_path
  end
end

app/helpers/product_requests_helper.rb
module ProductRequestsHelper
end

app/views/product_requests/edit.html.erb
<%= form_for(@product_request)  do |f| %>
  <% if @product_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_request.errors.count, "error") %> prohibited new products:</h2>
      <ul>
      <% @product_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :Street %>
  <%= f.text_field :street%>

  <%= f.label :City %>
  <%= f.text_field :city%>

  <%= f.label :state %>
  <%= f.select :state, Inquery::STATES%>

  <%= f.label :Zip_Code %>
  <%= f.text_field :zip%>

  <%= f.label :status %>
  <%= f.select :status, ProductRequest::STATUS%>

  <br />

  <%= f.submit "Submit Request", class: "btn-success" %>

<% end %>

app/views/product_requests/index.html.erb
<h2>Product Requests</h2>
 <%= page_entries_info @product_requests %>
 <%= will_paginate @product_requests, :renderer => BootstrapPagination::Rails %>
<% @product_requests.each do |product_request| %>
  <h5>Order Number: <%= product_request.id %></h5>
  <div class="row offset1">
    <div class="span3">
     <h6>Product: <%= product_request.product.name %></h6>
     <h6>Date: <%= time_ago_in_words(product_request.created_at) %> ago</h6>
    <h6>Status: <%= product_request.status %></h6>
    <h6>Quantity: <%= product_request.quantity %></h6>
     
    </div>
    <div class="span4">
      <h5>Address:</h5>
      <h6><%= product_request.user.first_name %> <%= product_request.user.last_name %> </h6>
      <h6><%= product_request.street%></h6>
      <h6><%= product_request.city%>, <%= product_request.state%> <%= product_request.zip%></h6>
    </div>
    <div class="span3">
      <p><%= link_to "Edit", edit_product_request_path(product_request) %></p>
      <p><%= link_to "Delete", product_request, method: "delete", :data => { :confirm => "Are you sure?" } %></p>
    </div>
  </div>
  <hr />
<% end %>

app/views/product_requests/new.html.erb
<h2>Product Request</h2>
<h3>Current Requests</h3>
<% @cart.cart_rows.each do |item| %> 
  <li><%= item.quantity %>&times; <b><%= item.product.name %></b> 
  <%= link_to "Remove", cart_row_path(item), method: "delete", :data => { :confirm => "Are you sure?" }%> 
<% end %>
<hr />
<h3>Shipping Address</h3>
<%= form_for(@product_request)  do |f| %>

  <% if @product_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_request.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
  <% @product_request.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

  <%= f.label :Street %>
  <%= f.text_field :street%>

  <%= f.label :City %>
  <%= f.text_field :city%>

  <%= f.label :state %>
  <%= f.select :state, Inquery::STATES%>

  <%= f.label :Zip_Code %>
  <%= f.text_field :zip%>

  <br />

  <%= f.submit "Submit Request", class: "btn-success" %>

<% end %>