config/routes.rb
Mavens::Application.routes.draw do

  devise_for :users

  resources :events
  resources :carts
  resources :periods
  resources :products
  resources :cart_rows
  resources :product_requests
  resources :inqueries
  match '/profile',  to: 'static_pages#profile'
  root :to => 'static_pages#home'

  get "static_pages/home"
  get "static_pages/about"
  post "static_pages/toggle_admin"
  match '/analytics', to: "static_pages#analytics"
  match '/list', to: "static_pages#user_index"

  resources :period_registrations do
  member do
    post :save_period
  end

  post :save_period, :on => :collection
end
  

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  date       :date
#  street     :string(255)
#  city       :string(255)
#  state      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Event < ActiveRecord::Base
  attr_accessible :city, :date, :name, :state, :street
  has_many :periods, dependent: :destroy

  validates :name, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates_date :date
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :require_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @events = Event.all.sort_by &:date
  end

  def show
    @event = Event.find(params[:id])
    @periods = Period.find_all_by_event_id(@event.id).sort_by &:start_time
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to events_url
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to events_url, flash: {success: "Product Request Updated!"}
    else
      render 'edit'
    end
  end

  def destroy
    event = Event.find(params[:id]).destroy
    flash[:success] = "Event Deleted."
    redirect_to events_url
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h2>Edit Event</h2>
<%= form_for(@event)  do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited new products:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :Name %>
  <%= f.text_field :name%>

  <%= f.label :date %>
  <%= f.text_field :date, id: "datepicker" %>

    <%= f.label :street %>
  <%= f.text_field :street %>

    <%= f.label :city %>
  <%= f.text_field :city %>

    <%= f.label :State %>
    <%= f.select :state, Inquery::STATES%>
<br />
<%= f.submit "Edit Event", class: "btn-success" %>
<% end %>

app/views/events/index.html.erb
<h2>Events List</h2>

<% @events.each do |event| %>
  <h3><%= link_to event.name, event_path(event) %> </h3>
  
    <% if user_signed_in? && current_user.admin?  %>
    <p><%= link_to "Edit Event", edit_event_path(event) %> | <%= link_to "Delete Event", event, method: "delete", :data => { :confirm => "Are you sure?"} %></p> 
  <% end %>

  <h5><%= event.date.strftime("%b %e, %Y") %> </h5>
  <h5><%= event.city%>, <%= event.state%> </h5>
  <br />
<% end %>

app/views/events/new.html.erb
<h2>New Event</h2>
<%= form_for(@event)  do |f| %>
  <% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
  <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
  <%= f.label :Name %>
  <%= f.text_field :name%>

  <%= f.label :date %>
  <%= f.text_field :date, id: "datepicker" %>

    <%= f.label :street %>
  <%= f.text_field :street %>

    <%= f.label :city %>
  <%= f.text_field :city %>

    <%= f.label :State %>
    <%= f.select :state, Inquery::STATES%>
<br />
<%= f.submit "Create Event", class: "btn-success" %>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<h5><%= @event.date.strftime("%b %e, %Y") %> </h5>
<h5><%= @event.street%> </h5>
<h5><%= @event.city%>, <%= @event.state%> </h5>

<br />

<h3>Sessions List</h3>

<% if !user_signed_in? %>
  <p>Please <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %> To Register for a Session<p>
<% end %>

<% @periods.each do | period | %>
<div class="span6">
    <p><b><%= period.name %></b> @ 
  <%= period.start_time.strftime("%l:%M") %> - <%= period.end_time.strftime("%l:%M %P") %> 

  <% if user_signed_in? && current_user.admin? %>
      <br />
         <%= link_to "Edit", edit_period_path(period) %> | 
         <%= link_to "Delete", period, method: "delete", :data => { :confirm => "Are you sure?"} %> | 
         <%= link_to "View Registered", period_path(period) %> | Registered: 
         <b><%= PeriodRegistration.find_all_by_period_id(period).count %></b>
  <% end %>

  <p><%= period.description %></p>
  <% if user_signed_in?  %>

    <% if PeriodRegistration.find_by_period_id_and_user_id(period, current_user) %>
      <%= link_to "Unregister For Session",period_registration_path(PeriodRegistration.find_by_period_id_and_user_id(period, current_user)), method: "delete", 
                                        :data => { :confirm => "Are you sure?"}, class: "btn btn-danger btn-small" %>
    <% else %>
    <%= link_to "Register for Session", save_period_period_registration_path(period_registration: {user_id: current_user.id, period_id: period.id}), 
        :method => :post, controller: "registrations", class: "btn btn-success btn-small" %>
    <% end %>
  <% end %>
  <hr />
</div>

<% end %>